# Generated by Django 4.2.2 on 2025-07-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
