# Generated by Django 4.2.2 on 2025-07-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Agent', 'Agent'), ('User', 'User'), ('Admin', 'Admin')], default='Agent', max_length=20),
        ),
    ]
