# Generated by Django 4.2.2 on 2025-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
