# Generated by Django 4.2.2 on 2024-03-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
