# Generated by Django 4.2.2 on 2024-04-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_profile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CAC',
            field=models.FileField(blank=True, upload_to='cac'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.FileField(blank=True, upload_to='national_id'),
        ),
    ]
