# Generated by Django 4.2.2 on 2024-04-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_profile_cac_profile_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='CAC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='national_id',
        ),
    ]
