# Generated by Django 4.2.2 on 2024-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0004_remove_profile_cac_remove_profile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
