# Generated by Django 4.2.2 on 2024-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0005_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
