# Generated by Django 4.2.2 on 2024-07-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0006_profile_contact_number2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=500)),
                ('name_on_account', models.CharField(max_length=500)),
                ('account_number', models.IntegerField(max_length=10)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Agents.profile')),
            ],
        ),
    ]
