# Generated by Django 4.2.2 on 2024-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0007_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
    ]
