# Generated by Django 4.2.2 on 2025-07-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0008_alter_bankdetails_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
