# Generated by Django 4.2.2 on 2024-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
