# Generated by Django 4.2.2 on 2024-02-17 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy'), ('Shortlet', 'Shortlet'), ('Land', 'Land')], default='Rent', max_length=50)),
                ('beds', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('toilets', models.IntegerField()),
                ('location', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Ogun', 'Ogun'), ('Port Harcourt', 'Port Harcourt')], default='Lagos', max_length=50)),
                ('district', models.CharField(blank=True, default='Ikeja', max_length=200)),
                ('furnished', models.BooleanField(blank=True, default=False)),
                ('newly_built', models.BooleanField(blank=True, default=False)),
                ('car_park', models.BooleanField(blank=True, default=False)),
                ('shared', models.BooleanField(blank=True, default=False)),
                ('swimming_pool', models.BooleanField(blank=True, default=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
