# Generated by Django 4.2.2 on 2024-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestprop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='prop_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Shortlet', 'Shortlet'), ('Land', 'Land')], default='Rent', max_length=50),
        ),
    ]
