# Generated by Django 4.2.2 on 2024-04-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestprop', '0002_alter_request_prop_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='max_price',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='request',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='request',
            name='car_park',
        ),
        migrations.RemoveField(
            model_name='request',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='request',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='request',
            name='newly_built',
        ),
        migrations.RemoveField(
            model_name='request',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='request',
            name='swimming_pool',
        ),
        migrations.RemoveField(
            model_name='request',
            name='toilets',
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
