# Generated by Django 4.2.2 on 2024-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestprop', '0003_rename_max_price_request_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Joint Venture', 'Joint Venture')], default='Rent', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='payment_plan',
            field=models.CharField(blank=True, choices=[('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('36 months', '36 months'), ('48 months', '48 months')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='sub_location',
            field=models.CharField(choices=[('Lagos Island', 'Lagos Island'), ('Lagos Mainland', 'Lagos Mainland')], default='Lagos Island', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(blank=True, choices=[('Lagos Island', 'Lagos Island'), ('Ikoyi', 'Ikoyi'), ('VI', 'VI'), ('Lekki Phase1/Ikate', 'Lekki Phase1/Ikate'), ('Jakande/Agungi/Chevron', 'Jakande/Agungi/Chevron'), ('Orchid/Ikota/VGC', 'Orchid/Ikota/VGC'), ('Ajah', 'Ajah'), ('Sangotedo', 'Sangotedo'), ('Abijo/Ibeju Lekki', 'Abijo/Ibeju Lekki'), ('Epe', 'Epe'), ('Apapa', 'Apapa'), ('Agege', 'Agege'), ('Alimosho/Ipaja', 'Alimosho/Ipaja'), ('Abule Egba/Agbado', 'Abule Egba/Agbado'), ('Ikeja', 'Ikeja'), ('Ogba/Ojodu/Berger', 'Ogba/Ojodu/Berger'), ('Magodo/Isheri/Arepo', 'Magodo/Isheri/Arepo'), ('Ojota/Ogudu', 'Ojota/Ogudu'), ('Maryland-Jibowu', 'Maryland-Jibowu'), ('Gbagada/Bariga/Somolu', 'Gbagada/Bariga/Somolu'), ('Yaba/Ebute Meta/Oyingbo', 'Yaba/Ebute Meta/Oyingbo'), ('Surulere/Iganmu', 'Surulere/Iganmu'), ('Oshodi/Isolo', 'Oshodi/Isolo'), ('Ojo/Mile 2/Mebamu', 'Ojo/Mile 2/Mebamu'), ('Ijaniki/Agbara', 'Ijaniki/Agbara'), ('Badagry/Araromi', 'Badagry/Araromi'), ('Ketu/Mile 12', 'Ketu/Mile 12'), ('Ikorodu', 'Ikorodu'), ('Sango Ota', 'Sango Ota')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='prop_type',
            field=models.CharField(choices=[('Detached Bungalows', 'Detached Bungalows'), ('Semi-Detached Bungalows', 'Semi-Detached Bungalows'), ('Terraced Bungalows', 'Terraced Bungalows'), ('Flat/Apartment', 'Flat/Apartment'), ('Detached Duplexes', 'Detached Duplexes'), ('Semi-Detached Duplexes', 'Semi-Detached Duplexes'), ('Terraced Duplexes', 'Terraced Duplexes'), ('Land', 'Land'), ('Shops', 'Shops'), ('Office Space', 'Office Space'), ('WareHouse', 'WareHouse'), ('Factory', 'Factory'), ('Complex', 'Complex'), ('Filling Station', 'Filling Station'), ('Tank Farm', 'Tank Farm'), ('Hotel', 'Hotel'), ('School', 'School'), ('Church', 'Church'), ('Hostel', 'Hostel'), ('Restaurant', 'Restaurant')], default='Bungalow', max_length=50),
        ),
    ]
