# Generated by Django 4.2.2 on 2024-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestprop', '0004_request_category_request_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='beds',
            field=models.IntegerField(blank=True),
        ),
    ]
