# Generated by Django 4.2.2 on 2024-07-27 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(max_length=6, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('timeslot', models.CharField(choices=[('8am-12pm', '8am-12pm'), ('1pm-5pm', '1pm-5pm')], default='9am-12pm', max_length=50)),
                ('prop_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_1', to='Favorites.favorite_property')),
                ('prop_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_2', to='Favorites.favorite_property')),
                ('prop_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_3', to='Favorites.favorite_property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
