# Generated by Django 4.2.2 on 2024-07-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0006_profile_contact_number2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture1', models.ImageField(upload_to='Properties')),
                ('picture2', models.ImageField(upload_to='Properties')),
                ('picture3', models.ImageField(upload_to='Properties')),
                ('picture4', models.ImageField(upload_to='Properties')),
                ('picture5', models.ImageField(blank=True, upload_to='Properties')),
                ('picture6', models.ImageField(blank=True, upload_to='Properties')),
                ('picture7', models.ImageField(blank=True, upload_to='Properties')),
                ('picture8', models.ImageField(blank=True, upload_to='Properties')),
                ('picture9', models.ImageField(blank=True, upload_to='Properties')),
                ('picture10', models.ImageField(blank=True, upload_to='Properties')),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True)),
                ('toilets', models.IntegerField(blank=True)),
                ('property_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('more_details', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Ogun', 'Ogun'), ('Port Harcourt', 'Port Harcourt')], default='Lagos', max_length=50)),
                ('sub_location', models.CharField(choices=[('Lagos Island', 'Lagos Island'), ('Lagos Mainland', 'Lagos Mainland')], default='Lagos Island', max_length=50)),
                ('district', models.CharField(blank=True, choices=[('Lagos Island', 'Lagos Island'), ('Ikoyi', 'Ikoyi'), ('VI', 'VI'), ('Lekki Phase1/Ikate', 'Lekki Phase1/Ikate'), ('Jakande/Agungi/Chevron', 'Jakande/Agungi/Chevron'), ('Orchid/Ikota/VGC', 'Orchid/Ikota/VGC'), ('Ajah', 'Ajah'), ('Sangotedo', 'Sangotedo'), ('Abijo/Ibeju Lekki', 'Abijo/Ibeju Lekki'), ('Epe', 'Epe'), ('Apapa', 'Apapa'), ('Agege', 'Agege'), ('Alimosho/Ipaja', 'Alimosho/Ipaja'), ('Abule Egba/Agbado', 'Abule Egba/Agbado'), ('Ikeja', 'Ikeja'), ('Ogba/Ojodu/Berger', 'Ogba/Ojodu/Berger'), ('Magodo/Isheri/Arepo', 'Magodo/Isheri/Arepo'), ('Ojota/Ogudu', 'Ojota/Ogudu'), ('Maryland-Jibowu', 'Maryland-Jibowu'), ('Gbagada/Bariga/Somolu', 'Gbagada/Bariga/Somolu'), ('Yaba/Ebute Meta/Oyingbo', 'Yaba/Ebute Meta/Oyingbo'), ('Surulere/Iganmu', 'Surulere/Iganmu'), ('Oshodi/Isolo', 'Oshodi/Isolo'), ('Ojo/Mile 2/Mebamu', 'Ojo/Mile 2/Mebamu'), ('Ijaniki/Agbara', 'Ijaniki/Agbara'), ('Badagry/Araromi', 'Badagry/Araromi'), ('Ketu/Mile 12', 'Ketu/Mile 12'), ('Ikorodu', 'Ikorodu'), ('Sango Ota', 'Sango Ota')], default='', max_length=200, null=True)),
                ('address', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Joint Venture', 'Joint Venture')], default='Rent', max_length=50)),
                ('prop_type', models.CharField(choices=[('Detached Bungalow', 'Detached Bungalow'), ('Semi-Detached Bungalow', 'Semi-Detached Bungalow'), ('Terraced Bungalow', 'Terraced Bungalow'), ('Flat/Apartment', 'Flat/Apartment'), ('Detached Duplex', 'Detached Duplex'), ('Semi-Detached Duplex', 'Semi-Detached Duplex'), ('Terraced Duplex', 'Terraced Duplex'), ('Residential Land', 'Residential Land'), ('Commercial Land', 'Commercial Land'), ('Mixed-Use Land', 'Mixed-Use Land'), ('Shop', 'Shop'), ('Office Space', 'Office Space'), ('WareHouse', 'WareHouse'), ('Factory', 'Factory'), ('Complex', 'Complex'), ('Filling Station', 'Filling Station'), ('Tank Farm', 'Tank Farm'), ('Hotel', 'Hotel'), ('School', 'School'), ('Church', 'Church'), ('Hostel', 'Hostel'), ('Restaurant', 'Restaurant')], default='Bungalow', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_options', models.CharField(choices=[('Asking Price', 'Asking Price'), ('Slightly Negotiable', 'Slightly Negotiable'), ('Net Price', 'Net Price'), ('Best Price', 'Best Price')], default='Asking Price', max_length=50)),
                ('furnished', models.BooleanField(blank=True, default=False)),
                ('Newly_built', models.BooleanField(blank=True, default=False)),
                ('Car_park', models.BooleanField(blank=True, default=False)),
                ('shared', models.BooleanField(blank=True, default=False)),
                ('swimming_pool', models.BooleanField(blank=True, default=False)),
                ('gym', models.BooleanField(blank=True, default=False)),
                ('electricity', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('under_contract', models.BooleanField(blank=True, default=False)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('serviced', models.BooleanField(blank=True, default=False, null=True)),
                ('inside_an_estate', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_options', models.CharField(blank=True, choices=[('6 months', '6 months'), ('12 months', '12 months'), ('18 months', '18 months'), ('24 months', '24 months'), ('36 months', '36 months'), ('48 months', '48 months')], max_length=200, null=True)),
                ('initial_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('video_available_on_request', models.BooleanField(blank=True, default=False)),
                ('other_amenities', models.TextField(blank=True, max_length=5000)),
                ('approved', models.BooleanField(default=False)),
                ('disapproved', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agents.profile')),
            ],
            options={
                'ordering': ['-agent__rating', '-created_at'],
            },
        ),
    ]
