# Generated by Django 4.2.2 on 2024-07-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Car_park',
            new_name='car_park',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Newly_built',
            new_name='newly_built',
        ),
    ]
