# Generated by Django 4.2.2 on 2024-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_car_park_property_car_park_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facilitator_fee',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='property',
            name='off_plan',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='premium',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='property',
            name='proposal',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='property',
            name='sharing_ratio',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_options',
            field=models.CharField(choices=[('Asking Price', 'Asking Price'), ('Slightly Negotiable', 'Slightly Negotiable'), ('Net Price', 'Net Price'), ('Best Price', 'Best Price'), ('Per Annum', 'Per Annum'), ('Per Month', 'Per Month'), ('Per Square Meter', 'Per Square Meter')], default='Asking Price', max_length=50),
        ),
    ]
