# Generated by Django 4.2.2 on 2024-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_facilitator_fee_property_off_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_type',
            field=models.CharField(choices=[('Detached Bungalow', 'Detached Bungalow'), ('Semi-Detached Bungalow', 'Semi-Detached Bungalow'), ('Terrace Bungalow', 'Terrace Bungalow'), ('Flat/Apartment', 'Flat/Apartment'), ('Detached Duplex', 'Detached Duplex'), ('Semi-Detached Duplex', 'Semi-Detached Duplex'), ('Terrace Duplex', 'Terrace Duplex'), ('Residential Land', 'Residential Land'), ('Commercial Land', 'Commercial Land'), ('Mixed-Use Land', 'Mixed-Use Land'), ('Shop', 'Shop'), ('Office Space', 'Office Space'), ('WareHouse', 'WareHouse'), ('Factory', 'Factory'), ('Complex', 'Complex'), ('Filling Station', 'Filling Station'), ('Tank Farm', 'Tank Farm'), ('Hotel', 'Hotel'), ('School', 'School'), ('Church', 'Church'), ('Hostel', 'Hostel'), ('Restaurant', 'Restaurant')], default='Bungalow', max_length=50),
        ),
    ]
