# Generated by Django 5.0.14 on 2025-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
