# Generated by Django 4.2.2 on 2024-06-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
